################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f64.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f64.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f64.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f64.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f64.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.c 

C_DEPS += \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f64.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f64.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f64.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f64.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f64.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.d 

CREF += \
proj_ra8p1_ruhmi.cref 

OBJS += \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f64.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f64.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f64.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f64.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f64.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.o 

MAP += \
proj_ra8p1_ruhmi.map 


# Each subdirectory must supply rules for building sources it contributes
ra/arm/CMSIS-DSP/Source/FilteringFunctions/%.o: ../ra/arm/CMSIS-DSP/Source/FilteringFunctions/%.c
	@echo 'Building file: $<'
	$(file > $@.in,-mcpu=cortex-m3 -mthumb -O0 -ffunction-sections -fdata-sections -fdiagnostics-parseable-fixits -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra_gen" -I"." -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra_cfg\\fsp_cfg\\bsp" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra_cfg\\fsp_cfg" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\src" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\fsp\\inc" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\fsp\\inc\\api" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\fsp\\inc\\instances" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\arm\\CMSIS_6\\CMSIS\\Core\\Include" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\fsp\\src\\rm_ethosu" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\npu\\flatbuffers\\include" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\arm\\CMSIS-NN\\Include" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\arm\\CMSIS-NN" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\npu\\ethos-u-core-software\\lib\\layer_by_layer_profiler\\include" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\npu\\ethos-u-core-software\\lib\\ethosu_monitor\\include" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\npu\\ethos-u-core-software\\lib\\ethosu_profiler\\include" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\npu\\ethos-u-core-driver\\include" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\arm\\CMSIS-DSP\\PrivateInclude" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\arm\\CMSIS-DSP\\Include" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\npu\\ruy" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\npu\\gemmlowp" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\npu\\tflite-micro" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\npu\\ethos-u-core-software\\lib\\crc\\include" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\npu\\ethos-u-core-software\\lib\\arm_profiler\\include" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\arm\\CMSIS-View\\EventRecorder\\Include" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\arm\\CMSIS-View\\EventRecorder\\Config" -I"D:/e2_workplace/proj_ra8p1_ruhmi/generate" -I"D:/e2_workplace/proj_ra8p1_ruhmi/generate" -I"D:/e2_workplace/proj_ra8p1_ruhmi/generate" -D_RENESAS_RA_ -D_RA_CORE=CPU0 -D_RA_ORDINAL=1 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" "$<" -c -o "$@")
	@clang --target=arm-none-eabi @"$@.in"

