/*
* Copyright (c) 2020 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/**********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : .
 **********************************************************************************************************************/

#include "hal_data.h"

#include "application_config.h"
#if defined(REQUIRE_OSPI_OPEN)
#include "ospi_b_ep.h"
#endif

#if defined(REQUIRE_OSPI_OPEN) && defined(REQUIRE_OSPI_MEMORY_COPY_TO_SDRAM)
extern uint32_t __sdram_from_ospi0_cs1$$Base;
extern uint32_t __sdram_from_ospi0_cs1$$Limit;
extern uint32_t __ddsc_OSPI0_CS1_END;
#endif

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* Do nothing. This function will not be called in RTOS enabled project. */
}

volatile uint32_t read_data[64];

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED
        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif

#if defined(REQUIRE_OSPI_OPEN)
        fsp_err_t err = ospi_b_init();
        if(err) return;

//        ospi_b_set_protocol_to_opi();

#if defined(REQUIRE_OSPI_MEMORY_COPY_TO_SDRAM)
        uint32_t data_length = (uint32_t) &__sdram_from_ospi0_cs1$$Limit - (uint32_t) &__sdram_from_ospi0_cs1$$Base;
        memcpy(&__sdram_from_ospi0_cs1$$Base, &__ddsc_OSPI0_CS1_END, data_length);
#endif
#endif
    }
}
