################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_q31.c 

C_DEPS += \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_q31.d 

CREF += \
proj_ra8p1_ruhmi.cref 

OBJS += \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_q31.o 

MAP += \
proj_ra8p1_ruhmi.map 


# Each subdirectory must supply rules for building sources it contributes
ra/arm/CMSIS-DSP/Source/StatisticsFunctions/%.o: ../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/%.c
	@echo 'Building file: $<'
	$(file > $@.in,-mcpu=cortex-m3 -mthumb -O0 -ffunction-sections -fdata-sections -fdiagnostics-parseable-fixits -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra_gen" -I"." -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra_cfg\\fsp_cfg\\bsp" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra_cfg\\fsp_cfg" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\src" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\fsp\\inc" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\fsp\\inc\\api" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\fsp\\inc\\instances" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\arm\\CMSIS_6\\CMSIS\\Core\\Include" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\fsp\\src\\rm_ethosu" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\npu\\flatbuffers\\include" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\arm\\CMSIS-NN\\Include" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\arm\\CMSIS-NN" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\npu\\ethos-u-core-software\\lib\\layer_by_layer_profiler\\include" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\npu\\ethos-u-core-software\\lib\\ethosu_monitor\\include" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\npu\\ethos-u-core-software\\lib\\ethosu_profiler\\include" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\npu\\ethos-u-core-driver\\include" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\arm\\CMSIS-DSP\\PrivateInclude" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\arm\\CMSIS-DSP\\Include" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\npu\\ruy" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\npu\\gemmlowp" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\npu\\tflite-micro" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\npu\\ethos-u-core-software\\lib\\crc\\include" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\npu\\ethos-u-core-software\\lib\\arm_profiler\\include" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\arm\\CMSIS-View\\EventRecorder\\Include" -I"D:\\e2_workplace\\proj_ra8p1_ruhmi\\ra\\arm\\CMSIS-View\\EventRecorder\\Config" -I"D:/e2_workplace/proj_ra8p1_ruhmi/generate" -I"D:/e2_workplace/proj_ra8p1_ruhmi/generate" -I"D:/e2_workplace/proj_ra8p1_ruhmi/generate" -D_RENESAS_RA_ -D_RA_CORE=CPU0 -D_RA_ORDINAL=1 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" "$<" -c -o "$@")
	@clang --target=arm-none-eabi @"$@.in"

